# DX 602 Week 7 Homework



## Introduction

In this homework, you will continue practicing the NumPy library to work with numbers in various ways.
There will be a particular focus on views, but you will also be asked to find and recognize relevant NumPy functions on your own.
NumPy is a large library with a lot of different functionality.
It is impractical to introduce each function individually, yet you will be able to make use of most of its functionality with a basic exercise of search skills.


## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [83]:
import math
import sys

In [84]:
import matplotlib.pyplot as plt
import numpy as np

## Problems

### Problem 1

Set `p1` to be `q1` flipped upside down.

In [85]:
# DO NOT CHANGE

q1 = np.array([[9, 1, 6], [2, 6, 3], [5, 0, 7]])

In [86]:
# YOUR CHANGES HERE

# Set p1 to be q1 flipped upside down
p1 = np.flipud(q1)

In [87]:
p1

array([[5, 0, 7],
       [2, 6, 3],
       [9, 1, 6]])

### Problem 2

Set `p2` to be the average value of `q2`.

In [88]:
# DO NOT CHANGE

q2 = np.array([[ 1.2710684 ,  0.34651747,  0.68960684, -1.12567075, -0.06412985,
         0.13373547,  0.84314528,  0.35206589],
       [-1.18745615,  0.50656175,  0.66699453,  0.72676468, -0.34165581,
        -1.00205835,  0.02101389,  0.93188219],
       [ 0.23127874, -0.32878023, -0.97939304,  0.01044438, -0.81895036,
        -0.44674951,  0.87667202, -1.51737553],
       [ 2.07266937, -1.63841334, -0.20043649,  1.01993301, -1.21509526,
        -0.15027553,  0.39621876,  0.28836095],
       [-0.83933974,  1.64994802, -0.1213623 ,  0.25179499,  1.0813766 ,
         0.48275638, -1.41171727, -0.72633164],
       [-0.38257196,  0.12212784,  0.73860358, -1.61096579, -0.38644903,
         0.30642748,  0.92550333, -2.20470762],
       [ 0.32864359,  0.8622356 ,  1.99156784,  0.2118577 , -0.58876625,
        -1.01185141,  0.83046577, -0.48243025],
       [ 0.31960012,  0.60696688,  0.68950522, -0.80539561, -1.04918003,
         0.2794904 , -0.09944267,  0.31027322]])
q2

array([[ 1.2710684 ,  0.34651747,  0.68960684, -1.12567075, -0.06412985,
         0.13373547,  0.84314528,  0.35206589],
       [-1.18745615,  0.50656175,  0.66699453,  0.72676468, -0.34165581,
        -1.00205835,  0.02101389,  0.93188219],
       [ 0.23127874, -0.32878023, -0.97939304,  0.01044438, -0.81895036,
        -0.44674951,  0.87667202, -1.51737553],
       [ 2.07266937, -1.63841334, -0.20043649,  1.01993301, -1.21509526,
        -0.15027553,  0.39621876,  0.28836095],
       [-0.83933974,  1.64994802, -0.1213623 ,  0.25179499,  1.0813766 ,
         0.48275638, -1.41171727, -0.72633164],
       [-0.38257196,  0.12212784,  0.73860358, -1.61096579, -0.38644903,
         0.30642748,  0.92550333, -2.20470762],
       [ 0.32864359,  0.8622356 ,  1.99156784,  0.2118577 , -0.58876625,
        -1.01185141,  0.83046577, -0.48243025],
       [ 0.31960012,  0.60696688,  0.68950522, -0.80539561, -1.04918003,
         0.2794904 , -0.09944267,  0.31027322]])

In [89]:
p2 = np.ndarray.mean(q2)

In [90]:
p2

np.float64(0.009955100156249994)

### Problem 3

Write a function `p3` that takes in a 2-dimensional array and returns an array with the even columns of the input array.


In [91]:
# YOUR CHANGES HERE

def p3(x):
    # The slice '::2' on the column axis (index 1) selects every 2nd column, 
    # starting from the 0th column (0, 2, 4, ...), which are the even-indexed columns.
    # The colon ':' for the row axis (index 0) selects all rows.
    return x[:, ::2]

In [92]:
# the output should have values [[0, 2, 4]]
p3(np.array([[0, 1, 2, 3, 4]]))

array([[0, 2, 4]])

In [93]:
p3(np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]))

array([[0, 2, 4],
       [5, 7, 9]])

### Problem 4

Write a function `p4` taking in a 2-dimensional array, and returning a 1-dimensional array with every 5th element of a row-order traversal of the input, starting from the 3rd element.

In [94]:
# YOUR CHANGES HERE

def p4(x):
    # 1. Flatten the 2D array x into a 1D array using the .ravel() method
    #    (This performs the "row-order traversal")
    flat_array = x.ravel()
    
    # 2. Slice the 1D array:
    #    - Start at index 2 (the 3rd element)
    #    - End is omitted (go to the end)
    #    - Step is 5 (select every 5th element)
    return flat_array[2::5]

In [95]:
x4 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
# this should return a 1-dimensional array with contents [2, 7, 12]

p4(x4)

array([ 2,  7, 12])

### Problem 5

What NumPy function evaluates the Einstein summation convention?
Set `p5` to be a reference to that function.
You can look for this function by using NumPy site documentation and search, or other search engines.

In [97]:
# YOUR CHANGES HERE

p5 = np.einsum

In [98]:
p5

<function einsum at 0x78dd10d31fb0>

### Problem 6

Write a function `p6` that takes in two inputs, a function and an array, and returns `True` if calling that function with the array as input returns a view of that array and `False` otherwise.

In [99]:
# YOUR CHANGES HERE

def p6(f, x):
    # 1. Call the function f with the array x as input
    y = f(x)
    
    # 2. Check if y is a view of x.
    #    A view's 'base' property points to the array whose data it shares.
    #    If y.base is 'x', it means y is a view directly on x's data.
    
    return y.base is x

In [100]:
p6(np.sum, np.arange(20))

False

In [101]:
p6(np.fliplr, np.zeros((3, 4)))

True

### Problem 7

Write a function `p7` that takes in an array, and if it is a view, returns a number indicating the proportion of the original array that is seen through the view, and returns `None` if the array is not a view.
If the input is an array of 10 elements, and it is a view of an array of 20 elements, your function should return 0.5.


In [102]:
# YOUR CHANGES HERE

def p7(x):
    # Step 1: Check if the array is a view.
    # A view has a 'base' that points to the original array (or the base of the base).
    if x.base is None:
        return None
    else:
        # Step 2: Calculate the proportion.
        # x.size is the number of elements in the current view.
        # x.base.size is the number of elements in the original array being viewed.
        proportion = x.size / x.base.size
        return proportion

In [103]:
# a view

t7a = np.arange(20)
t7b = t7a[::2]
p7(t7b)

0.5

In [104]:
# not a view

p7(np.arange(20))

### Problem 8

Write a function `p8` that returns the diagonal of an input 2-dimensional array. The diagonal of an array $x$ is the elements $x[0][0], x[1][1], x[2][2], \ldots$.


In [105]:
# YOUR CHANGES HERE

def p8(x):
    # np.diag(x) extracts the main diagonal (where row index = column index)
    return np.diag(x)

In [106]:
p8(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

array([1, 5, 9])

### Problem 9

Write a function `p9` that returns a view of the diagonal of an input 2-dimensional array but it must return a view of the original array. (If your previous answer already returned a view, you may reuse it.)

In [107]:
# YOUR CHANGES HERE

def p9(x):
    # The .diagonal() method returns a VIEW of the specified diagonal 
    # for 2D arrays, satisfying the requirement.
    return x.diagonal()

In [108]:
x9 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [109]:
p9(x9)

array([0, 4, 8])

In [110]:
# uncomment to test after you finish p9

p9(x9).base is x9

True

### Problem 10

The [$X + Y$ sorting problem](https://en.wikipedia.org/wiki/X_%2B_Y_sorting) considers the problem of sorting pairs of numbers from two lists of numbers, $X$ and $Y$, by their sums.
Write a function `p10` that takes in two 1-dimensional arrays, $x$ and $y$, and returns a two dimensional array $z$ such that $z[i,j] = x[i] + y[j]$.

Hint: use broadcasting.

In [111]:
# YOUR CHANGES HERE

def p10(x, y):
    # To use broadcasting to get z[i, j] = x[i] + y[j]:
    # 1. Reshape x to be a column vector (N, 1). This corresponds to x[i].
    # 2. Keep y as a row vector (1, M). This corresponds to y[j].
    # When these are added, broadcasting expands them to a result of shape (N, M).
    
    # x[:, np.newaxis] changes the shape from (N,) to (N, 1)
    # y remains (M,) which NumPy interprets as (1, M) during broadcasting
    return x[:, np.newaxis] + y

In [112]:
p10(np.array([10, 20, 30]), np.array([1, 2, 3, 4, 5]))

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

### Problem 11

Write a function `p11` taking an $n \times k$ array and returns an $n \times 3$ array where the first column is the minimum value of the input rows, the second column is the median of the input rows, and the third column is the maximum values of the input rows.


Hint: there was a similar problem in week 6, but you will need `numpy.reshape` and `numpy.hstack` to adapt those results.


In [113]:
def p11(x):
    # Calculate statistics along the rows (axis=1)
    min_vals = np.min(x, axis=1)
    median_vals = np.median(x, axis=1)
    max_vals = np.max(x, axis=1)
    
    # Reshape each 1D result from (n,) to a column vector (n, 1)
    n = x.shape[0] # Get the number of rows
    
    min_col = np.reshape(min_vals, (n, 1))
    median_col = np.reshape(median_vals, (n, 1))
    max_col = np.reshape(max_vals, (n, 1))
    
    # Horizontally stack the column vectors to form the final (n, 3) array
    return np.hstack((min_col, median_col, max_col))

In [114]:
p11(np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]]))

array([[ 0.,  2.,  4.],
       [ 5.,  7.,  9.],
       [10., 12., 14.]])

### Problem 12

What does the following code do?

```
def f12(vs):
    return [v for (i, v) in enumerate(vs) if i >= 5]

def g12(n):
    for i in range(n):
        yield i ** 2

print(f12(g12(10)))
```

Set `p12` to the printed output.

In [115]:
# YOUR CHANGES HERE

p12 = [25, 36, 49, 64, 81]

In [116]:
p12

[25, 36, 49, 64, 81]

### Problem 13

The following code is supposed to iterate the Collatz function until it reaches the value 1, but does not have the correct control flow.
Modify the loop below so that it continues until the last entry of `p13` is one.

In [117]:
# DO NOT CHANGE

def f13(x):
    if x % 2 == 0:
        # even case
        return x // 2
    else:
        return 3 * x + 1

In [118]:
# DO NOT CHANGE

p13 = [27]

In [119]:
# YOUR CHANGES HERE

while p13[-1] != 1:
    # apply f13() to the last entry of p13.
    p13.append(f13(p13[-1]))

In [120]:
p13

[27,
 82,
 41,
 124,
 62,
 31,
 94,
 47,
 142,
 71,
 214,
 107,
 322,
 161,
 484,
 242,
 121,
 364,
 182,
 91,
 274,
 137,
 412,
 206,
 103,
 310,
 155,
 466,
 233,
 700,
 350,
 175,
 526,
 263,
 790,
 395,
 1186,
 593,
 1780,
 890,
 445,
 1336,
 668,
 334,
 167,
 502,
 251,
 754,
 377,
 1132,
 566,
 283,
 850,
 425,
 1276,
 638,
 319,
 958,
 479,
 1438,
 719,
 2158,
 1079,
 3238,
 1619,
 4858,
 2429,
 7288,
 3644,
 1822,
 911,
 2734,
 1367,
 4102,
 2051,
 6154,
 3077,
 9232,
 4616,
 2308,
 1154,
 577,
 1732,
 866,
 433,
 1300,
 650,
 325,
 976,
 488,
 244,
 122,
 61,
 184,
 92,
 46,
 23,
 70,
 35,
 106,
 53,
 160,
 80,
 40,
 20,
 10,
 5,
 16,
 8,
 4,
 2,
 1]

### Problem 14

Set `p14` to be the shape tuple of the variable `q14` at the end of the following code.

```
q14 = np.arange(24)
q14 = q14.reshape(3, -1)
q14 = q14[:,::3]
```

In [142]:
# YOUR CHANGES HERE

p14 = (3, 3) 

In [143]:
p14

(3, 3)

### Problem 15

The array `q15` below was filled with a sample of random numbers.
The variable `p15` is a reference to the same array.
Change the contents of `p15` so that the first row is all zeros.
After your change to `p15`, the variables `p15` and `q15` should still be the same array.

Hint: use row indexing to easily overwrite just one row of `p15`.

In [123]:
# DO NOT CHANGE

q15 = np.array([[ 1.76435665, -0.66892705, -1.08485379, -0.51982851,  1.2362559 ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])
p15 = q15
p15

array([[ 1.76435665, -0.66892705, -1.08485379, -0.51982851,  1.2362559 ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])

In [124]:
# YOUR CHANGES HERE

# Select the first row (index 0) of the array p15
# and assign an array of zeros with the same shape as that row.
p15[0, :] = 0

In [125]:
p15

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.15524724, -0.78679294, -0.9343088 ,  2.78526049,  0.19342893],
       [ 0.76716362,  2.91044894, -0.80492143, -1.63290739, -0.50503081],
       [ 0.09743684,  0.11846846,  1.0413396 ,  0.85669315,  0.30437891],
       [ 0.56113285, -1.02444355, -1.57142929,  0.251055  , -1.09196046]])

In [126]:
# confirm that p15 is still the same array
id(p15) == id(q15)

True

### Problem 16

Write a function `p16` that takes in numbers of rows and columns and a value, and uses `np.broadcast_to` to make a 2-dimensional array of the specified size that appears to have the specified dimensions and each has the given value.
This will be similar to the output of `np.full`, except the resulting array will be read-only because of the broadcast usage.

In [127]:
# YOUR CHANGES HERE

def p16(rows, columns, value):
    # 1. Create a 0-dimensional array containing only the single 'value'.
    # This array has a shape of ().
    scalar_array = np.array(value)
    
    # 2. Define the target shape for the 2D array.
    target_shape = (rows, columns)
    
    # 3. Use np.broadcast_to to create a view that expands the scalar_array 
    #    to the target shape.
    return np.broadcast_to(scalar_array, target_shape)

In [128]:
t16 = p16(3, 4, 5)
t16

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Problem 17

Set `p17` to the contents of `q17` after running the following code.

```
q17 = np.arange(16)
q17 = q17.reshape(-1, 4)
q17 = np.flipud(q17)
q17 = np.fliplr(q17)
```

In [129]:
# YOUR CHANGES HERE

p17 = np.array([[15, 14, 13, 12],
                [11, 10, 9, 8],
                [ 7,  6,  5,  4],
                [ 3,  2,  1,  0]])

In [130]:
p17

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### Problem 18

Write a function `p18` that takes in a size $n$ and returns a 1-dimensional array of length $n$ where the first element is $1$ and the $i+1$th element is the $i$th element plus $1/(i+1)$.
Make sure to test your function on at least $n=1000000$.

In [148]:
# YOUR CHANGES HERE

def p18(n):
    if n == 0:
        return np.array([], dtype=float)
    
    # Initialize the array
    arr = np.zeros(n, dtype=float)
    arr[0] = 1.0  # The first element is 1 (0-indexed)
    
    # Loop from the second element (index 1) up to n-1
    for j in range(1, n):
        # j is the 0-based index of the element being calculated (a_{j+1})
        # The recurrence relation uses the 1-based index i.
        # j-th element = (j-1)-th element + 1 / (i * (i+1))
        # Here, i (1-based index of the PREVIOUS term) is j.
        # So, the j-th element (a_{j+1}) uses i = j (the index of the previous term)
        i = j  
        arr[j] = arr[j-1] + (1.0 / (i * (i + 1)))
        
    return arr


In [149]:
# should return array with contents [1, 1.5]
p18(2)

array([1. , 1.5])

In [150]:
p18(5)

array([1.        , 1.5       , 1.66666667, 1.75      , 1.8       ])

In [151]:
# this will be very slow if your function repeatedly builds fresh arrays.
p18(1000000)

array([1.        , 1.5       , 1.66666667, ..., 1.999999  , 1.999999  ,
       1.999999  ], shape=(1000000,))

### Problem 19

Write a function `p19` that takes in 3 values $a$, $b$, and $c$ and an array $X$ and returns $a X^2 + bX + c$.
`p19` should return an array in the same shape as the input $X$.

In [135]:
# YOUR CHANGES HERE

def p19(a, b, c, X):
    # The exponentiation (X**2) is element-wise.
    # The multiplication by scalars (a, b) is element-wise (broadcasting).
    # The final addition of the scalar c is also element-wise (broadcasting).
    return a * (X ** 2) + b * X + c


In [136]:
p19(1, 0, 0, np.arange(0, 10))

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [137]:
p19(0, 0, 1, np.arange(0, 10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [138]:
p19(1, 2, 3, np.arange(0, 10))

array([  3,   6,  11,  18,  27,  38,  51,  66,  83, 102])

### Problem 20

Write a function `p20` taking in input array $X$ and return $X X^T$ where $X^T$ denotes matrix transposition, and $X X^T$ denotes combining $X$ and $X^T$ with matrix multiplication.


In [139]:
# YOUR CHANGES HERE

def p20(X):
    # X.T is the transpose of X
    # The @ operator performs matrix multiplication (np.matmul or np.dot for 2D arrays)
    return X @ X.T
    
    # Alternatively:
    # return np.dot(X, X.T)

In [140]:
# should return
# [[1, 2, 3, 4, 5],
#  [2, 4, 6, 8, 10],
#  [3, 6, 9, 12, 15],
#  [4, 8, 12, 16, 20],
#  [5, 10, 15, 20, 25]]

p20(np.array([[1], [2], [3], [4], [5]]))


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [141]:
# should return
# [[ 2,  3,  4,  5,  6],
#  [ 3,  5,  7,  9, 11],
#  [ 4,  7, 10, 13, 16],
#  [ 5,  9, 13, 17, 21],
#  [ 6, 11, 16, 21, 26]]

p20(np.array([[1, 1], [2, 1], [3, 1], [4, 1], [5, 1]]))

array([[ 2,  3,  4,  5,  6],
       [ 3,  5,  7,  9, 11],
       [ 4,  7, 10, 13, 16],
       [ 5,  9, 13, 17, 21],
       [ 6, 11, 16, 21, 26]])